version: '3'
#--init-file /data/application/init.sql
#- ./init.sql:/data/application/init.sql
# docker-entrypoint-initdb.d.

services:
  db:
    image: mysql:5.7
    command : --innodb-use-native-aio=0
    container_name : db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-node-db
  
  server:
    build: 
      context: ./node/ 
    container_name: server
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks:
      - nginx-node-db
    volumes:
      - ./node:/node
      - /node/node_modules
    depends_on:
        - db
    
  proxy:
    build:
      context: ./nginx_proxy/
    container_name: proxy-nginx
    restart: always
    networks:
      - nginx-node-db
    ports:
      - 8080:8080

networks:
  nginx-node-db:
    driver: bridge